Update README.md
versatus/versatus-javascript pull request #28
Opened 2023-12-28 20:09 UTC by Ghlee433

referenced rust repo to update js repo!

2023-12-28 22:29 UTC, mattgeddes requested changes
A great start! Fantastic job, mate! A couple of comments for things to change/clarify.

2023-12-28 22:29 UTC, mattgeddes commented on README.md
> +In the JavaScript ecosystem, you can leverage WebAssembly to compile your JavaScript code to a format that is compatible with the Versatus smart contract runtime. This allows you to write smart contr
Web Assembly *is* the format we're compiling to. The tool to do the compilation isn't to Web Assembly is called Javy.

2023-12-28 22:29 UTC, mattgeddes commented on README.md
> +Javy is a JavaScript to WebAssembly toolchain that can create small Wasm modules in the 1 to 16 KB range with the use of dynamic linking. The toolchain aims to be a verstaile tool for anyone who want
Typo: versatile.

WASM is an acronym, so should be written as 'WASM', not 'Wasm'.

The 1-16kB stuff seems pretty small compared with the contracts we've been building -- do we have a reference for that?

2023-12-28 23:02 UTC, Ghlee433 commented on README.md
> +Javy is a JavaScript to WebAssembly toolchain that can create small Wasm modules in the 1 to 16 KB range with the use of dynamic linking. The toolchain aims to be a verstaile tool for anyone who want
updating for versatile and WASM! good catch, thank you.

1-16kb source: https://github.com/bytecodealliance/javy
under 'About this repo': Javy can create very small Wasm modules in the 1 to 16 KB range with use of dynamic linking. The default static linking produces modules that are at least 869 KB in size.

2023-12-28 23:04 UTC, Ghlee433 commented on README.md
> +In the JavaScript ecosystem, you can leverage WebAssembly to compile your JavaScript code to a format that is compatible with the Versatus smart contract runtime. This allows you to write smart contr
I see where I wrote that incorrectly. will update!

2023-12-29 01:56 UTC, mattgeddes commented on README.md
> +Javy is a JavaScript to WebAssembly toolchain that can create small Wasm modules in the 1 to 16 KB range with the use of dynamic linking. The toolchain aims to be a verstaile tool for anyone who want
OK. I get the 1-16kB comment now. We actually have developers (for all languages) statically link their contracts instead of dynamically because it reduces dependencies that need to be managed either by us or by them. We will look at more of a dynamically linked approach with WASM components once there's better support for that, but for now with Javy, it's statically linked. I would remove everything after _small WASM modules_ in that sentence. Props for proactively seeking out potentially useful info though.

2023-12-29 02:17 UTC, mattgeddes requested changes
I think we're getting close. Thanks a bunch.

2023-12-29 02:17 UTC, mattgeddes commented on README.md
> +Yarn -
One more small nit. Can we change Node, Yarn and Javy to subneadings to stand out more when rendered?

For example, instead of `Node - Node.js is....`, making it:

```
#### Node

Node.js is a....
```

2023-12-29 02:17 UTC, mattgeddes commented on README.md
> +Javy is a JavaScript to WebAssembly toolchain that can create small WASM modules in the 1 to 16 KB range with the use of dynamic linking. The toolchain aims to be a versatile tool for anyone who want
For the XX on the end of the line here (installing Javy), feel free to add a section for this below somewhere and validate that it works. The high level steps to follow would be to:

1. Download the latest version of the Javy package for your platform from the Bytecode Alliance Github page (https://github.com/bytecodealliance/javy/releases/)
2. Decompress the downloaded file using `gunzip` or another tool capable of decompressing gzip-format files (eg, `gunzip javy-x86_64-macos-v1.2.0.gz`
3. Make the Javy binary executable (ie, `chmod a+x javy-x86_64-macos-v1.2.0`)
4. Optionally place the Javy binary somewhere in your PATH (eg, /usr/local/bin or ~/bin) and rename it to simply `javy` (ie, `mv javy-x86_64-macos-v1.2.0 /usr/local/bin/javy` to do both in one command.
5. Test that it can be executed by running it, including the path to the executable if needed (ie `./javy` or `/usr/local/bin/javy` or simply `javy`).

Executing it without any arguments should show the usage output. Or `javy --version` should show the version number, also indicating it works.

Does that sound alright?

2023-12-29 03:19 UTC, Ghlee433 commented on README.md
> +Javy is a JavaScript to WebAssembly toolchain that can create small WASM modules in the 1 to 16 KB range with the use of dynamic linking. The toolchain aims to be a versatile tool for anyone who want
yas! ty!

2023-12-29 15:14 UTC, hathbanger commented on README.md
> +Javy is a JavaScript to WebAssembly toolchain that can create small WASM modules in the 1 to 16 KB range with the use of dynamic linking. The toolchain aims to be a versatile tool for anyone who want
@Ghlee433 @mattgeddes should we remove the installation we have during sys_check.sh? It's not very robust in that it's not REALLY checking the system for os or anything else

https://github.com/versatus/versatus-javascript/blob/main/lib/scripts/sys-check.sh#L4-L25

2023-12-29 15:35 UTC, hathbanger commented on README.md
> +Javy is a JavaScript to WebAssembly toolchain that can create small WASM modules in the 1 to 16 KB range with the use of dynamic linking. The toolchain aims to be a versatile tool for anyone who want
we could perhaps just check for it using `which` and then if it's not installed, tell them to read the README

2023-12-29 17:02 UTC, mattgeddes requested changes
So close!

2023-12-29 17:02 UTC, mattgeddes commented on README.md
> +2. Decompress the downloaded file using gunzip or another tool capable of decompressing gzip-format files (eg, gunzip javy-x86_64-macos-v1.2.0.gz
Can we wrap each of the sample commands in `backticks` to have it rendered with a fixed-width font? Just makes it easier to see the specific syntax with certain characters.

2024-01-02 20:24 UTC, mattgeddes approved these changes
Looks good to me! Ship it! You ought to be able to hit a button down the bottom to either squash and merge or rebase and merge. Whatever the default is ought to be fine I think. It'll then let you delete the branch, which you should do (it removes it from github and avoids clutter). Congratulations!

2024-01-02 21:53 UTC, merged